version: '3.8'

services:
  mindmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindmap-github
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mindmap-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mindmap-network:
    driver: bridge