version: '3.8'

services:
  mindmap:
    build: .
    container_name: mindmap-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # volumes:
      # 如果需要持久化某些配置，可以挂载卷
      # - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - mindmap-network

networks:
  mindmap-network:
    driver: bridge