# 移除version字段，因为它在最新版本的Docker Compose中已过时
services:
  mind-map:
    build:
      context: .
      dockerfile: Dockerfile
      # 添加构建参数以加速构建过程
      args:
        - BUILDKIT_INLINE_CACHE=1
      # 使用BuildKit加速构建
      x-bake:
        platforms: ["linux/amd64"]
        cache-from:
          - type=registry,ref=mind-map:cache
    container_name: mind-map
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # 可选：如果需要持久化存储数据
      - ./data:/app/data
    environment:
      # 可选：配置环境变量
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - mind-map-network

networks:
  mind-map-network:
    driver: bridge